language: cpp
sudo: required

matrix:
    include:
# Linux Build
        - os: linux
          compiler: g++
          dist: bionic
          env: CXX_TOOLS=g++

# Cross-compile Build for Linux via mingw64
        - os: linux
          compiler: x86_64-w64-mingw32-g++
          env: CXX_TOOLS=x86_64-w64-mingw32-g++
          dist: bionic
          addons:
              apt:
              packages:
                  - gcc-mingw-w64-base
                  - binutils-mingw-w64-x86-64
                  - gcc-mingw-w64-x86-64
                  - gcc-mingw-w64
                  - g++-mingw-w64-x86-64

# Build for macOS via GCC
        - os: osx
          osx_image: xcode8
          env:
            - MATRIX_EVAL="brew install gcc && CC_TOOLS=gcc-7 && CXX_TOOLS=g++-7"

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then eval "${MATRIX_EVAL}" ; fi

script:
    - "./tools/compile_travis.sh"

